# Generated by Django 4.2.3 on 2023-08-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destino', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destino',
            old_name='foto',
            new_name='foto1',
        ),
        migrations.AddField(
            model_name='destino',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
        migrations.AddField(
            model_name='destino',
            name='meta',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='destino',
            name='text_descritivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
