# Generated by Django 4.2.3 on 2023-08-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destino', '0002_rename_foto_destino_foto1_destino_foto2_destino_meta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='meta',
            field=models.CharField(max_length=160),
        ),
    ]
