# Generated by Django 4.2.3 on 2023-08-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destino', '0003_alter_destino_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='text_descritivo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
